// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwgtxvlmhmddhuqqmeaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Z3R4dmxtaG1kZGh1cXFtZWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTg5OTUsImV4cCI6MjA0OTk3NDk5NX0.zKHFjclraJbh4NJaThNtdST6cUreUaTGzEn6E7mf_7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);